### PR TITLE
Add symfony 3.0 support

### PR DESCRIPTION
**Pull request by Ener-Getick**
This PR is based on top of #505 and adds symfony 3.0 support.

A new method ``VoteInterface::isValid`` is created to support the new validator context interface signature.

The build fail is caused by FOSRestBundle ([a bug fix will be applied soon](https://github.com/FriendsOfSymfony/FOSRestBundle/pull/1250))

### CODE REVIEW

**Comment by Ener-Getick** [comment]
It remains only one job failing: https://travis-ci.org/FriendsOfSymfony/FOSCommentBundle/jobs/99749727.
May someone help me to find the issue happening here?

**Comment by Ener-Getick** [comment]
The tests are fixed

**Comment by XWB** [comment]
Excellent, thank you :)

**Comment by salemgolemugoo** [comment]
I have an issue. When I try to add a vote to some comment, an error appears:
```
[1] Symfony\Component\Debug\Exception\ContextErrorException: Notice: Undefined index: value
    at n/a
        in /var/www/site/vendor/friendsofsymfony/comment-bundle/FOS/CommentBundle/Constraints/LegacyCallbackHelper.php line 25

    at Symfony\Component\Debug\ErrorHandler->handleError('8', 'Undefined index: value', '/var/www/site/vendor/friendsofsymfony/comment-bundle/FOS/CommentBundle/Constraints/LegacyCallbackHelper.php', '25', array('options' => array('methods' => array('isVoteValid'))))
        in /var/www/site/vendor/friendsofsymfony/comment-bundle/FOS/CommentBundle/Constraints/LegacyCallbackHelper.php line 25

    at FOS\CommentBundle\Constraints\LegacyCallbackHelper->__construct(array('methods' => array('isVoteValid')))
        in /var/www/site/vendor/symfony/symfony/src/Symfony/Component/Validator/Mapping/Loader/AbstractLoader.php line 89

    at Symfony\Component\Validator\Mapping\Loader\AbstractLoader->newConstraint('FOS\CommentBundle\Constraints\LegacyCallbackHelper', array('methods' => array('isVoteValid')))
        in /var/www/site/vendor/symfony/symfony/src/Symfony/Component/Validator/Mapping/Loader/XmlFileLoader.php line 92

    at Symfony\Component\Validator\Mapping\Loader\XmlFileLoader->parseConstraints(object(SimpleXMLElement))
        in /var/www/site/vendor/symfony/symfony/src/Symfony/Component/Validator/Mapping/Loader/XmlFileLoader.php line 203

    at Symfony\Component\Validator\Mapping\Loader\XmlFileLoader->loadClassMetadataFromXml(object(ClassMetadata), object(SimpleXMLElement))
        in /var/www/site/vendor/symfony/symfony/src/Symfony/Component/Validator/Mapping/Loader/XmlFileLoader.php line 56

    at Symfony\Component\Validator\Mapping\Loader\XmlFileLoader->loadClassMetadata(object(ClassMetadata))
        in /var/www/site/vendor/symfony/symfony/src/Symfony/Component/Validator/Mapping/Loader/LoaderChain.php line 57

    at Symfony\Component\Validator\Mapping\Loader\LoaderChain->loadClassMetadata(object(ClassMetadata))
        in /var/www/site/vendor/symfony/symfony/src/Symfony/Component/Validator/Mapping/Loader/LoaderChain.php line 57

    at Symfony\Component\Validator\Mapping\Loader\LoaderChain->loadClassMetadata(object(ClassMetadata))
        in /var/www/site/vendor/symfony/symfony/src/Symfony/Component/Validator/Mapping/Factory/LazyLoadingMetadataFactory.php line 126

    at Symfony\Component\Validator\Mapping\Factory\LazyLoadingMetadataFactory->getMetadataFor('FOS\CommentBundle\Model\Vote')
        in /var/www/site/vendor/symfony/symfony/src/Symfony/Component/Validator/Mapping/Factory/LazyLoadingMetadataFactory.php line 114

    at Symfony\Component\Validator\Mapping\Factory\LazyLoadingMetadataFactory->getMetadataFor('FOS\CommentBundle\Entity\Vote')
        in /var/www/site/vendor/symfony/symfony/src/Symfony/Component/Validator/Mapping/Factory/LazyLoadingMetadataFactory.php line 114

    at Symfony\Component\Validator\Mapping\Factory\LazyLoadingMetadataFactory->getMetadataFor(object(Vote))
        in /var/www/site/vendor/symfony/symfony/src/Symfony/Component/Validator/Validator/RecursiveContextualValidator.php line 340

    at Symfony\Component\Validator\Validator\RecursiveContextualValidator->validateObject(object(Vote), 'data', array('Default'), '1', object(ExecutionContext))
        in /var/www/site/vendor/symfony/symfony/src/Symfony/Component/Validator/Validator/RecursiveContextualValidator.php line 155

    at Symfony\Component\Validator\Validator\RecursiveContextualValidator->validate(object(Vote), null, 'Default')
        in /var/www/site/vendor/symfony/symfony/src/Symfony/Component/Form/Extension/Validator/Constraints/FormValidator.php line 51

    at Symfony\Component\Form\Extension\Validator\Constraints\FormValidator->validate(object(Form), object(Form))
        in /var/www/site/vendor/symfony/symfony/src/Symfony/Component/Validator/Validator/RecursiveContextualValidator.php line 843

    at Symfony\Component\Validator\Validator\RecursiveContextualValidator->validateInGroup(object(Form), '00000000150c1acc000000000d05f1e8', object(ClassMetadata), 'Default', object(ExecutionContext))
        in /var/www/site/vendor/symfony/symfony/src/Symfony/Component/Validator/Validator/RecursiveContextualValidator.php line 554

    at Symfony\Component\Validator\Validator\RecursiveContextualValidator->validateClassNode(object(Form), '00000000150c1acc000000000d05f1e8', object(ClassMetadata), '', array('Default'), null, '1', object(ExecutionContext))
        in /var/www/site/vendor/symfony/symfony/src/Symfony/Component/Validator/Validator/RecursiveContextualValidator.php line 360

    at Symfony\Component\Validator\Validator\RecursiveContextualValidator->validateObject(object(Form), '', array('Default'), '1', object(ExecutionContext))
        in /var/www/site/vendor/symfony/symfony/src/Symfony/Component/Validator/Validator/RecursiveContextualValidator.php line 155

    at Symfony\Component\Validator\Validator\RecursiveContextualValidator->validate(object(Form), null, null)
        in /var/www/site/vendor/symfony/symfony/src/Symfony/Component/Validator/Validator/RecursiveValidator.php line 117

    at Symfony\Component\Validator\Validator\RecursiveValidator->validate(object(Form))
        in /var/www/site/vendor/symfony/symfony/src/Symfony/Component/Form/Extension/Validator/EventListener/ValidationListener.php line 55

    at Symfony\Component\Form\Extension\Validator\EventListener\ValidationListener->validateForm(object(FormEvent), 'form.post_bind', object(EventDispatcher))
        in  line 

    at call_user_func(array(object(ValidationListener), 'validateForm'), object(FormEvent), 'form.post_bind', object(EventDispatcher))
        in /var/www/site/var/cache/dev/classes.php line 1756

    at Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(array(array(object(ValidationListener), 'validateForm'), array(object(DataCollectorListener), 'postSubmit')), 'form.post_bind', object(FormEvent))
        in /var/www/site/var/cache/dev/classes.php line 1671

    at Symfony\Component\EventDispatcher\EventDispatcher->dispatch('form.post_bind', object(FormEvent))
        in /var/www/site/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/ImmutableEventDispatcher.php line 43

    at Symfony\Component\EventDispatcher\ImmutableEventDispatcher->dispatch('form.post_bind', object(FormEvent))
        in /var/www/site/vendor/symfony/symfony/src/Symfony/Component/Form/Form.php line 655

    at Symfony\Component\Form\Form->submit(array('value' => '1', '_token' => 'TMn6jNiFiEH3kP6u449G7c5x2zUxLCjA94aMGf4rXwY'), true)
        in /var/www/site/vendor/symfony/symfony/src/Symfony/Component/Form/Extension/HttpFoundation/HttpFoundationRequestHandler.php line 116

    at Symfony\Component\Form\Extension\HttpFoundation\HttpFoundationRequestHandler->handleRequest(object(Form), object(Request))
        in /var/www/site/vendor/symfony/symfony/src/Symfony/Component/Form/Form.php line 488

    at Symfony\Component\Form\Form->handleRequest(object(Request))
        in /var/www/site/vendor/friendsofsymfony/comment-bundle/FOS/CommentBundle/Controller/ThreadController.php line 581

    at FOS\CommentBundle\Controller\ThreadController->postThreadCommentVotesAction(object(Request), 'salon_5', '2')
        in  line 

    at call_user_func_array(array(object(ThreadController), 'postThreadCommentVotesAction'), array(object(Request), 'salon_5', '2'))
        in /var/www/site/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php line 139

    at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), '1')
        in /var/www/site/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php line 62

    at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), '1', true)
        in /var/www/site/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php line 169

    at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
        in /var/www/site/web/app_dev.php line 30
```

**Comment by Ener-Getick** [comment]
@Soullivaneuh we have to merge #535 then it's ok for me :-)

**Pull request merged**
