### PR TITLE
Add the ability to use a custom db_driver.

### PR DESCRIPTION
**Pull request by MartialGeek**
Hello

I propose this PR to allow the non-Doctrine users to use a custom db_driver (as in the FOSUserBundle config).
Obviously, this option is usable only when the user declares at least the model classes and the manager services in its bundle configuration :

```yml
fos_comment:
    db_driver: custom
    class:
        model:
            comment: Vendor\Bundle\Entity\Comment
            thread: Vendor\Bundle\Entity\Thread
            vote: Vendor\Bundle\Entity\Vote
    service:
        manager:
            comment: vendor.comment.comment_manager
            thread: vendor.comment.thread_manager
            vote: vendor.comment.vote_manager
```

### CODE REVIEW

**Comment by xavierleune** [comment]
:+1:

**Comment by ndesaleux** [comment]
:+1:

**Comment by oxman** [comment]
:+1:

**Comment by xavierleune** [comment]
Ping @XWB :smiley:

**Comment by oxman** [comment]
Ping @XWB :)

**Comment by namesash** [comment]
:+1:

**Comment by XWB** [comment]
Thanks :)

**Comment by oxman** [comment]
Thanks @XWB

**Comment by MartialGeek** [comment]
Great! Thank you guys ;)

**Comment by xavierleune** [comment]
Thks @XWB for the merge & the release!

**Comment by namesash** [comment]
Thanks guys

**Pull request merged**
