### PR TITLE
Bump vendors

### PR DESCRIPTION
**Pull request by XWB**

### CODE REVIEW

**Comment by ymaerschalck** [comment]
hi @XWB I was wondering if and when you have time to complete this pull request and release it? 
We are still using your bundle and would like to upgrade to symfony 5 with it.

**Comment by XWB** [comment]
I would need some help with this, I cannot get FOSRestBundle 3.x to work with bundle :(

**Comment by ymaerschalck** [comment]
And what seems to be the problem with FOSRest?

**Comment by ymaerschalck** [comment]
@XWB how can I help you with this?

**Comment by treehousedevelopers** [comment]
Here are changes for FOS Rest 3.x https://github.com/treehousedevelopers/FOSCommentBundle/commits/4.x. 

PHP 8.x is required

You need to enable html format in the FOS REst configuration.

**Comment by XWB** [comment]
Thank you @treehousedevelopers

**Pull request closed without merging**
