### PR TITLE
FIx constraint Symfony3 & Hydrate User

### PR DESCRIPTION
**Pull request by tdubuffet**
I've made the corrections to issues #538 (Fix constraint Symfony 3) & #526 (Hydrate User)

### CODE REVIEW

**Comment by Ener-Getick** [comment]
:+1: for the constraint

**Comment by XWB** [comment]
Any idea why the tests fail?

**Comment by tdubuffet** [comment]
No idea probably the version Of Symfony...
I'm on version 3.1.3

**Comment by XWB** [comment]
@tdubuffet Can you separate both commits and create two pull requests instead? It's difficult to determine which commit causes the tests to fail.

**Comment by XWB** [comment]
https://github.com/FriendsOfSymfony/FOSCommentBundle/pull/562 https://github.com/FriendsOfSymfony/FOSCommentBundle/pull/563

**Pull request closed without merging**
