### PR TITLE
SF3 compatibility

### PR DESCRIPTION
**Pull request by AetherFox**
Some additions to the code posted by @Ener-Getick , made to make the integration of this bundle to the SF3 projects easier. You can consult the https://github.com/Ener-Getick/FOSCommentBundle/pull/1 PR for more info.

### CODE REVIEW

**Comment by XWB** [comment]
Some tests are failing.

**Comment by cedricziel** [comment]
Seems to be a packagist/composer related issue since the composer.json hasnt been changed and the builds don't fail because of the tests but early on composer install.

Could you just restart the build please?

**Comment by XWB** [comment]
Done, thanks @AetherFox :)

**Comment by cedricziel** [comment]
Great, thank you guys!

**Pull request merged**
