### PR TITLE
Updates needed for FOSRestBundle 2.0

### PR DESCRIPTION
**Pull request by tarjei**
This does not break anything:
* Remove RouteRedirectView -> use View::createRouteRedirect

This breaks installations of Symfony 2.3:
* Change from using Codes::HTTP_* constants to Response::HTTP_ constants

Symfony 2.3 support ends in may this year.

### CODE REVIEW

**Comment by Filoz** [comment]
Hi, will it be merged?

**Comment by Ener-Getick** [comment]
I think it's better to copy the ``Codes`` class from FOSRestBundle for now with only the codes we need.
This way we can still support sf 2.3 and only drop its support when we decide to.

**Comment by tarjei** [comment]
How about just adding local constants for those constants in `Codes` that are used?

**Comment by Ener-Getick** [comment]
Yeah this is what i meant @tarjei ☺

**Comment by tarjei** [comment]
OK, I'm sorry that this took so long, but here is an updated version with the codes hardcoded :)

**Comment by stof** [comment]
Given that Symfony 2.3 support has already ended, we can drop support though

**Comment by tarjei** [comment]
I suggest we do that in a later PR :)

**Comment by tarjei** [comment]
The failing check seems to be due to an unrelated composer issue - or am I missing something?

**Comment by XWB** [comment]
Thanks :)

**Comment by XWB** [comment]
@Phobetor Can you have a look at https://github.com/FriendsOfSymfony/FOSCommentBundle/pull/591 ?

**Comment by Phobetor** [comment]
@XWB If compatibility with older symfony versions is not an issue, that solves the problem.
As long as `symfony/framework-bundle` 2.3 is supported, the `Response::HTTP_` constants cannot be used.

**Comment by XWB** [comment]
@Phobetor Symfony 2.3 support has been dropped in the master branch. The 2.x branch will not be changed.

**Comment by Phobetor** [comment]
@XWB I see. Given that, #591 solves the issue for future 3.x and the issue will persist until that is released.

**Pull request merged**
