### PR TITLE
Update syntax to the new one in 2.6

### PR DESCRIPTION
**Pull request by tarjei**
change from factory-service and factory-method to a separate <factory>
element.

### CODE REVIEW

**Comment by XWB** [comment]
I'm not sure if this will work with Symfony 2.3?

**Comment by tarjei** [comment]
Neither am I.

How important is 2.3 vs 2.7?

Also, I saw there are some other failings wrt SecurityContextInterface that also is deprecated. An alternative would be to create a stable tag for 2.3 support and let master support 2.6+

**Comment by XWB** [comment]
Symfony 2.3 is a LTS version, IMO we should keep supporting it until official support ends.

I created a PR to resolve all deprecated messages while keeping Symfony 2.3 support: https://github.com/FriendsOfSymfony/FOSCommentBundle/pull/475

**Comment by tarjei** [comment]
Hmm, we're in a bind here then, as 2.7 is an LTS version as well as I understand it :)

I guess the best way forward is to support two different branches then, right?

**Comment by XWB** [comment]
Yes, both 2.3 and 2.7 are LTS versions.

Maintaining two different branches is rather painful, the above PR supports both 2.3 and 2.7.

**Comment by tarjei** [comment]
As long as you can get that working I'm all for it :P

2015-06-04 15:37 GMT+02:00 Karel <notifications@github.com>:

> Yes, both 2.3 and 2.7 are LTS versions.
>
> Maintaining two different branches is rather painful, the above PR
> supports both 2.3 and 2.7.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FriendsOfSymfony/FOSCommentBundle/pull/474#issuecomment-108900861>
> .
>



-- 
__________________
Tarjei Huse
Mobil: 920 63 413

**Comment by tarjei** [comment]
I saw that #475 does not fix the issues brought up in this thread - thought they are also deprecation warnings. Do you have a plan for how to solve that? Maybe keep different files depending on the symfony version?

**Comment by XWB** [comment]
What kind of errors are you still getting?

**Comment by XWB** [comment]
Deprecated warnings have been fixed in https://github.com/FriendsOfSymfony/FOSCommentBundle/pull/475

Feel free to open a new issue if you find more deprecated warnings.

**Pull request closed without merging**
